### ISSUE TITLE
RCV1-2 dataset

### ISSUE THREAD

**Issue by Chriszhangmw** [wzh9969/HPT#1]
Thanks for your amazing work. 
we followed your instruction to get the RCV1-2 datasets, and the owner approved our requests as follows:
![image](https://user-images.githubusercontent.com/52879076/199634915-1660ce51-2fe2-48e6-a260-e9bc74ac194e.png)
but we always get error in preprocessing during extracting files from tar, so could you help to send us the processed dataset for our next training experiment?   thanks
email :
zhangmwchris@gamil.com

**Comment by wzh9969** [comment]
The extracting part is from [this repo](https://github.com/ductri/reuters_loader). Open an issue there if you have any questions. Anyway, I have sent you the processed dataset after running all my scripts.

**Comment by Chriszhangmw** [comment]
got it, thank you so much
