### ISSUE TITLE
运行环境问题

### ISSUE THREAD

**Issue by Vvvvvvsysy** [wzh9969/HPT#3]
我本地环境是torch1.8.1+torch-geometric1.7.2+torch-scatter2.0.8+torch-sparse0.6.12 
他在graph.py的194行报错，layer_emb = self.graph(label_emb.squeeze(00, edge_index=extra_attn)
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling 'cublasCreate(handle)'
是我环境的问题吗？

**Comment by wzh9969** [comment]
可能是环境问题，我试过的最高torch版本是1.8.0，没有测试过更高版本。

**Comment by Vvvvvvsysy** [comment]
那你能把你使用的环境给我一份吗？readme里面写的不太明确。

**Comment by wzh9969** [comment]
torch 1.8.0, transformers 4.18.0，torch-geometric相关已在readme里说明。理论上torch版本应是向前兼容的，所以readme里没有指定版本。
