### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by wjczf123** [wzh9969/HPT#4]
Hi, zihan.

I have a question about this paper. For verbalizer, you create a learnable virtual label word for each label. In this way, this method is very much like a traditional MLM task. Is my understanding correct?

**Comment by wzh9969** [comment]
Yes, it's correct. The key idea of prompt is to form downstream tasks as the pretraining task, which is MLM in the case of BERT.

**Comment by wjczf123** [comment]
Thank you for your reply.
