### ISSUE TITLE
BERT 参数在训练中冻结了吗？

### ISSUE THREAD

**Issue by liulu1998** [wzh9969/HPT#5]
在您代码 `models/prompt.py` 中的 `Prompt` 中使用了 BERT，请问 BERT 权重是否冻结了，BERT 参数也是可更新的吗 ？  

若没有冻结，参考刘知远老师 _"PPT: Pre-trained Prompt Tuning for Few-shot Learning"_，`HPT` 的训练方式是 `Prompt-oriented Fine-tuning` 吗 ？

![image](https://user-images.githubusercontent.com/48306835/223354158-eb4bfa32-ea13-4bf8-bf16-2443ab56bfe7.png)

谢谢！

**Comment by wzh9969** [comment]
BERT参数没有冻结，属于图中的c方式。

**Comment by liulu1998** [comment]
谢谢回复！
