### ISSUE TITLE
Label Hierarchy

### ISSUE THREAD

**Issue by anj3412** [wzh9969/HPT#8]
Hi,
Could you please clear that this HPT model works for Label hierarchy from root node to leaf node only?
Suppose a document does not belong to leaf node in the label hierarchy but belong to internal node. Then, this HPT model will give the label hierarchy from root node to internal node or not?

**Comment by wzh9969** [comment]
The model can predict from the root node to an internal node. The model architecture and training data have no limitation on where to end the prediction so predicting a set of labels without any leaf node is possible.
