### ISSUE TITLE
NYT Dataset

### ISSUE THREAD

**Issue by peyote-e** [wzh9969/HPT#9]
Hi there, 

thank you for providing the code! 
My question is regarding the New York Times dataset. How many samples of the 1.5 million articles did you use to train and how many and how long did a epoch train for?
I don't have acess to the NYT dataset, but I tryed training with my own dataset which had 400k articles and a one training epoch took 3 hours and the prediction took 14 h. I stopped at one epoch because I could not estimate how long it would take in total.

All the best!

**Comment by wzh9969** [comment]
Hi, data statistics are listed in Appendix A in the paper. For NYT, the training set has around 23k passages.

**Comment by peyote-e** [comment]
Thank you
